CREATE TABLE [dbo].[tblACOCApertura] (
    [id]                NUMERIC (18)  NULL,
    [idPresto]          NUMERIC (18)  NULL,
    [noCredito]         NVARCHAR (50) NULL,
    [cr]                NVARCHAR (50) NULL,
    [importe]           NVARCHAR (50) NULL,
    [tipoCredito]       NVARCHAR (50) NULL,
    [ctaCheques]        NVARCHAR (50) NULL,
    [comApertura]       NVARCHAR (50) NULL,
    [idPeriodicidad]    INT           NULL,
    [tasa]              NVARCHAR (50) NULL,
    [cat]               NVARCHAR (50) NULL,
    [modalidad]         NVARCHAR (50) NULL,
    [moneda]            NVARCHAR (50) NULL,
    [plazo]             NVARCHAR (50) NULL,
    [idGracia]          INT           NULL,
    [formaPago]         NVARCHAR (50) NULL,
    [idTipoCargo]       INT           NULL,
    [noCaso]            NVARCHAR (50) NULL,
    [fechaPrimerPago]   NVARCHAR (50) NULL,
    [opcionPrepago]     NVARCHAR (50) NULL,
    [idPagoIVA]         INT           NULL,
    [gastosInvest]      NVARCHAR (50) NULL,
    [seguroDesempleo]   NVARCHAR (50) NULL,
    [baseCalculoSeguro] NCHAR (13)    NULL,
    [ValorVivienda]     NVARCHAR (50) NULL,
    [pzoPagaBcoSeguro]  INT           NULL,
    [idBonificacion]    INT           NULL
);

