CREATE TABLE [dbo].[tblACOCDisposicion] (
    [id]                      NUMERIC (18)  NULL,
    [idPresto]                NUMERIC (18)  NULL,
    [noCredito]               NVARCHAR (50) NULL,
    [fechaDisposicion]        DATE          NULL,
    [importe]                 NVARCHAR (50) NULL,
    [montoDisposicion]        NVARCHAR (50) NULL,
    [comisionMinistracion]    NVARCHAR (50) NULL,
    [idComision]              INT           NULL,
    [gastosinvest]            NVARCHAR (50) NULL,
    [idFormaPago]             NVARCHAR (50) NULL,
    [fechaFirma]              NVARCHAR (50) NULL,
    [montoChequeCaja]         NVARCHAR (50) NULL,
    [cuentaConcentradora]     NVARCHAR (50) NULL,
    [fechaVigencia]           NVARCHAR (50) NULL,
    [nombreVendedor]          NVARCHAR (50) NULL,
    [nombreNotario]           NVARCHAR (50) NULL,
    [noCtaChequesAcred]       NVARCHAR (50) NULL,
    [idPagoVendedor]          INT           NULL,
    [idTipoPagoVendedor]      NVARCHAR (30) NULL,
    [ctaChequesVendedor]      NVARCHAR (30) NULL,
    [importePagoVendedor]     NVARCHAR (50) NULL,
    [importeGastosNotario]    NVARCHAR (50) NULL,
    [cuentaHonorariosNotario] NVARCHAR (50) NULL,
    [noCuenta]                NVARCHAR (50) NULL,
    [tipoCaso]                NVARCHAR (50) NULL,
    [crSucursal]              NVARCHAR (50) NULL,
    [tipoCredito]             NVARCHAR (50) NULL,
    [modalidad]               NVARCHAR (50) NULL,
    [nombreCliente]           NVARCHAR (50) NULL,
    [numeroCredito]           NVARCHAR (50) NULL,
    [noAcreditado]            NVARCHAR (50) NULL
);

