CREATE TABLE [dbo].[tblDatosDomicilio] (
    [id]                  NUMERIC (18)   NULL,
    [idPresto]            NUMERIC (18)   NULL,
    [tipoParticipante]    NVARCHAR (50)  NULL,
    [calle]               NVARCHAR (100) NULL,
    [numero]              NCHAR (10)     NULL,
    [dirColoniaPoblacion] NVARCHAR (100) NULL,
    [codCiudad]           NVARCHAR (100) NULL,
    [municipio]           NVARCHAR (50)  NULL,
    [estado]              NVARCHAR (50)  NULL,
    [pais]                NVARCHAR (50)  NULL,
    [codigoPostal]        INT            NULL,
    [tipoDomicilio]       NVARCHAR (50)  NULL,
    [tipoVivienda]        NVARCHAR (100) NULL,
    [departamento]        NVARCHAR (100) NULL,
    [mail]                NVARCHAR (100) NULL,
    [tipo_tel1]           NVARCHAR (50)  NULL,
    [telefono1]           NVARCHAR (30)  NULL,
    [ext1]                NVARCHAR (30)  NULL,
    [tipo_tel2]           NVARCHAR (30)  NULL,
    [telefono2]           NVARCHAR (30)  NULL,
    [ext2]                NVARCHAR (30)  NULL,
    [tipo_tel3]           NVARCHAR (30)  NULL,
    [telefono3]           NVARCHAR (30)  NULL,
    [ext3]                NVARCHAR (30)  NULL
);

