CREATE TABLE [dbo].[tblDatosOperacion] (
    [id]                      NUMERIC (18)    NULL,
    [idPresto]                NUMERIC (18)    NULL,
    [idSubproducto]           NVARCHAR (50)   NULL,
    [idProgramaConvenio]      INT             NULL,
    [idDestinoCredito]        INT             NULL,
    [idGpoPlazo]              INT             NULL,
    [idPlazo]                 INT             NULL,
    [idCondicionSpecial]      INT             NULL,
    [idModalidad]             INT             NULL,
    [idTipoTasa]              INT             NULL,
    [idTipoComision]          INT             NULL,
    [idComisionInvestigacion] NVARCHAR (50)   NULL,
    [idMoneda]                INT             NULL,
    [importe]                 DECIMAL (12, 2) NULL,
    [valorEstimadoInmueble]   DECIMAL (18)    NULL,
    [comisionApertura]        DECIMAL (18)    NULL,
    [comisionAdmin]           NVARCHAR (30)   NULL,
    [comisionMinistracion]    NVARCHAR (30)   NULL,
    [comisionPrepago]         NVARCHAR (30)   NULL,
    [comInvest]               NVARCHAR (30)   NULL,
    [ivacominvest]            INT             NULL,
    [seguroGen]               NVARCHAR (50)   NULL,
    [idlsReferenciaBroker]    INT             NULL,
    [idUsuarioBroker]         NVARCHAR (30)   NULL,
    [idFranquiciaBroker]      NVARCHAR (30)   NULL,
    [idAsesorBroker]          NVARCHAR (30)   NULL,
    [idCorredorInmobiliario]  INT             NULL,
    [idFranquiciaCl]          INT             NULL,
    [idAsesorInmobiliario]    INT             NULL,
    [idCanalVentas]           INT             NULL,
    [folio]                   NVARCHAR (50)   NULL,
    [fuerzaGanadora]          NVARCHAR (30)   NULL,
    [valorPrimerInmueble]     DECIMAL (18)    NULL,
    [valorSegInmueble]        DECIMAL (18)    NULL,
    [valorTercerInmueble]     DECIMAL (18)    NULL,
    [ecotecnologia]           NVARCHAR (50)   NULL
);

