CREATE TABLE [dbo].[tblGarantias] (
    [id]                     NUMERIC (18)   NULL,
    [idPresto]               NUMERIC (18)   NULL,
    [noGarantia]             INT            NULL,
    [esPromotor]             INT            NULL,
    [propietario]            NVARCHAR (50)  NULL,
    [idMarcaComercial]       NVARCHAR (50)  NULL,
    [ejecutivo]              NVARCHAR (100) NULL,
    [calleNum]               NVARCHAR (50)  NULL,
    [colonia]                NVARCHAR (50)  NULL,
    [ciudad]                 NVARCHAR (20)  NULL,
    [estado]                 NVARCHAR (50)  NULL,
    [codigoPostal]           INT            NULL,
    [ubicacion]              NVARCHAR (50)  NULL,
    [idTipoInmueble]         INT            NULL,
    [lote]                   NCHAR (3)      NULL,
    [manzana]                NCHAR (3)      NULL,
    [m2construccion]         DECIMAL (6, 2) NULL,
    [m2terreno]              DECIMAL (6, 2) NULL,
    [ruv]                    INT            NULL,
    [latitud]                DECIMAL (2, 2) NULL,
    [longitud]               DECIMAL (2, 2) NULL,
    [idEsDomicilioTitular]   INT            NULL,
    [idEsGarantiaCony]       INT            NULL,
    [idGarantiaFuePropiedad] INT            NULL
);

